dependencies:
  - python>=3.10,<3.11
  - torch==2.1.0
  - torchvision==0.16.0
  - torchdata
  - openbabel
  - pdbfixer
  - swig
  - setuptools==69.5.1
  - huggingface_hub
  - jupyter
  - notebook
  - transformers
  - pandas
  - datasets
  - biopython==1.80
  - scikit-learn
  - matplotlib
  - evaluate
  - simplejson
  - accelerate
  - py3dmol
  - fair-esm


